### ISSUE TITLE
Add collaborators of transferred repo.

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-battle-detail#16]
似乎 transfer 过来的 repo 其他组没有权限... 加一个？
cc @KochiyaOcean @magicae

**Comment by KochiyaOcean** [comment]
![image](https://cloud.githubusercontent.com/assets/8194131/11275731/0ac67164-8f1a-11e5-8416-6f3ad4a65921.png)
你确定？

**Comment by yukixz** [comment]
咦0 0 那他们说没有权限更改、不太清楚了=。= 
cc @taroxd @Ayaphis

**Comment by Ayaphis** [comment]
那天@taroxd说给tg加监听加不上O O,权限不足？
