### ISSUE TITLE
[联动] 开放接口，可以在日志中选择某场战斗然后查看详情

### ISSUE THREAD

**Issue by JenningsWu** [poooi/plugin-battle-detail#22]
### 想法
可以在日志中选择某一场战斗，然后跳转到战斗详情里查看该场战斗的详情。

### 实现
* 日志和详情均保存了战斗开始时的 timestamp，可以以这个为关键字关联日志中的战斗记录和战斗详情保存的战斗包。
* poi 最近（计划）实装的 ipc 模块提供了插件间通信的一种方法。战斗详情插件可以开放一个 `showBattleWithTimestamp` 接口，日志调用这个接口，传入战斗的 timestamp 等数据。

#### 接口的传入信息
* 该场战斗 timestamp
* 因保存的 timestamp 可能存在偏差，可以额外传入该场战斗地图点等信息，用于匹配战斗。日志可以传入的参数包括：
  * 海域、地图点、敌舰队名称
  * 旗舰名称（日文）与等级

#### 接口的返回信息（回调函数）
接口可以通过回调函数，返回执行结果。传入参数可以为一个 int code，内容为：
* 未找到匹配战斗
* 找到匹配战斗
* ……

**Comment by yukixz** [comment]
按 timestamp 匹配就好啦=。= 不存在有人能三四秒内进行两场战斗（有就是开挂！

**Comment by yukixz** [comment]
这个 API 按一下流程工作：
1. 找战斗包
2.1 如果找到：显示、并 focus 详情插件。
2.2 如果没找到：什么都不做
3. 调用 callback，传入 error code。

这样子？

**Comment by JenningsWu** [comment]
嗯。
focus 由调用者做还是详情插件自己做？

**Comment by yukixz** [comment]
自己做=。=

**Comment by yukixz** [comment]
话说这样错误信息分开处理了是不是不好=。=
要不我直接传个 error message 到 callback、然后航海日志直接显示出来就行了？

**Comment by JenningsWu** [comment]
行

**Comment by yukixz** [comment]
@JenningsWu 做好啦=。=

**Comment by yukixz** [comment]
`ipc.access('BattleDetail').showBattleWithTimestamp(timestamp, callback(message))`

**Comment by JenningsWu** [comment]
wow！（睡醒起来做

**Comment by yukixz** [comment]
测试了下、大概需要 700ms 的调用时间、瓶颈在 `glob.sync`。
明晚我优化一下。
cc @JenningsWu

**Comment by JenningsWu** [comment]
赞

**Comment by yukixz** [comment]
哦！ 我都忘了要优化了...

**Comment by yukixz** [comment]
Done. 响应时间优化到 50ms.
