### ISSUE TITLE
2.2.0的战斗详情有bug

### ISSUE THREAD

**Issue by smlrx1** [poooi/plugin-battle-detail#30]
我打5-4，仅第一个点有航空战数据，炮击和鱼雷都没有数据了，后面两个点就直接没有记录了。重装了好几次也不行。
打3-2-A也是仅有航空战数据，剩下的也没有了。
还有现在演戏也没有战斗详情了吗？希望能加回该功能
POI 6.2.0 x64 windows 10

**Comment by yukixz** [comment]
更新 2.3.0

演习看心情、不怎么打算加
