### ISSUE TITLE
增加战斗回放功能

### ISSUE THREAD

**Issue by midare16** [poooi/plugin-battle-detail#34]
能不能做个回放功能，或者导出文件到KanColle Battle Replayer 那里回放。

**Comment by gnattu** [comment]
其实我们有一个：https://github.com/Gizeta/poi-plugin-battle-replay
不过这个还没有为7.9的改动作好准备

**Comment by Gizeta** [comment]
虽然不知道是不是因为 7.9 的改动，不过 [poi-plugin-battle-replay](https://github.com/Gizeta/poi-plugin-battle-replay) 确实因为 jQuery 的问题坏掉了。已修。

![default](https://user-images.githubusercontent.com/1572561/29620351-4aa309e2-8850-11e7-9a5f-31459275096a.png)

感觉现在最大的问题是UI（抄的旧版battle-detail一直懒得改 \_(:з)∠)\_
