### ISSUE TITLE
无法记录夜转昼的战斗

### ISSUE THREAD

**Issue by SykieChen** [poooi/plugin-battle-detail#36]
![image](https://user-images.githubusercontent.com/5460009/33316666-a9cc7e74-d46f-11e7-805c-f78a7539174f.png)
如图，E4P3的 boss 战无法记录。道中各点正常。似乎是因为夜转昼？

**Comment by SykieChen** [comment]
哦抱歉，看起来是记录下来了，但无法在航海日志里直接唤起，我去那边再提个 issue。
打扰了！

**Comment by KagamiChan** [comment]
@SykieChen 请说一下你的 poi 的和各个插件的版本号

**Comment by SykieChen** [comment]
@KagamiChan 
航海日志 6.1.4
战斗记录 3.7.6
本体 8.0.0 beta 2

我试试更新本体到正式版

**Comment by SykieChen** [comment]
@KagamiChan 另外夜转昼详情里昼战还是排在夜战之前
![download](https://user-images.githubusercontent.com/5460009/33317745-07f2343c-d473-11e7-9f02-9e17108b15fa.png)
