### ISSUE TITLE
Cannot share data with Akashic-records?

### ISSUE THREAD

**Issue by Wafer-Li** [poooi/plugin-battle-detail#4]
![qq 20151020015619](https://cloud.githubusercontent.com/assets/12459199/10584676/570e5564-76ce-11e5-9eb5-0980a61059cb.png)

**Comment by yukixz** [comment]
No.
akashic-records didnt save the detailed battle packet.

**Comment by Wafer-Li** [comment]
I think, since the two plugins are both bundled plugins for poi, they can
share the same data to improve the performence.

2015-10-20 2:03 GMT+09:00 Dazzy Ding <notifications@github.com>:

**Comment by yukixz** [comment]
Seem like that, but in fact these two plugins have no relationship.

Akashic records show you the battle result that retrieved from `/battleresult` API.
Battle detail show you the detail of a battle. Its data retrieved from `/battle` API.

In another way, the battle detail plugin needs to simulate the battle to get the detailed attack process every time, but akashic records only concern on the final result of the battle.

**Comment by Wafer-Li** [comment]
Do you means that the data of this plugins are from a **simulate** progress, in another way, the data is **NOT 100% correct**?

**Comment by yukixz** [comment]
How can you associate simulation with not correct..?

**Comment by dkwingsmt** [comment]
"Simulation" here simply means to replay the battle process based on what was given by the game server. Every information used is guaranteed to be authentic and official. Nothing is provided by guessing.

**Comment by yukixz** [comment]
Here I give you some data.
```
Start Status:
A 100HP, B 120HP
Attacks:
A attack B: 10 damage.
B attack A: 20 damage.
A attack B: 12 damage.
A attack B: 14 damage.
```
Now, how much HP does B have? Dont you need a simulation process?

**Comment by Wafer-Li** [comment]
Because the whole back-end of kancolle is a black box, isn't it?
2015年10月20日 上午1:33，"Dazzy Ding" <notifications@github.com>写道：

**Comment by Wafer-Li** [comment]
oh, I see.
I misunderstood the "simulation" as you simulate the battle progress base
on the konwn theory.

It is really hard to type on phone. please close the issue.

Thanks for replying.
2015年10月20日 上午1:40，"omysho mulakami" <omyshokami@gmail.com>写道：

**Comment by Chibaheit** [comment]
The attack process was retrieved from /battle API. We only need to make a simulation to get the result.
