### ISSUE TITLE
poi更新react-bootstrap后‘标题栏’显示错误导致战斗概况无法打开

### ISSUE THREAD

**Issue by slime7** [poooi/plugin-battle-detail#41]
poi sha: 4312f098ba48b13c60cf6981ccb176bc14d99e85
跟新此版本后的情况: ‘战斗概况’, '战斗详情'的标题会不可见。
更新前dom及界面截图(poi sha: d39a62d7194e11fcd5c040c02e4a8e05fe20e0f2): 
![1](https://user-images.githubusercontent.com/8674371/34859656-9643e108-f792-11e7-8bd2-da43aa833743.png)
跟新后以上情况: 
![2](https://user-images.githubusercontent.com/8674371/34859850-341d8e64-f794-11e7-826e-6be8c67a044c.png)

**Comment by KochiyaOcean** [comment]
由于是 Breaking Change，需要插件更新
