### ISSUE TITLE
可以做一个单独窗口的未卜先知吗？

### ISSUE THREAD

**Issue by deepsea666** [poooi/plugin-battle-detail#50]
现在poi的8.2.0可以把主面板分三列了，调整后可以把整个屏幕下方空出来，这样的话可以把插件放下面，只要把战斗的敌我分成左右显示，窗口应该可以放得下，如果可以和主窗口粘接，可以同步最小化和显示就更理想了
![4566](https://user-images.githubusercontent.com/21211204/36883193-72f16c3c-1e13-11e8-8a58-bc1be7cc5fca.jpg)

**Comment by KochiyaOcean** [comment]
@deepsea666 难

**Comment by deepsea666** [comment]
难就算了吧，实在不行我放弃使用切分面板吧

**Comment by KochiyaOcean** [comment]
如果想要改变布局为上下切分仍然可以使用自定义 CSS（height 比率请自行调整）
https://pastebin.com/YC9FV4cS
对于特定布局而言调整的难度比较低，做成通用模块则相当有难度，目前情况下暂时不考虑
