### ISSUE TITLE
关于上下切分面板后的布局

### ISSUE THREAD

**Issue by deepsea666** [poooi/plugin-battle-detail#51]
![165489](https://user-images.githubusercontent.com/21211204/36936547-ff8d7c24-1f41-11e8-80d2-8b688ea100ec.png)

还是老问题，高度不够，如果能有一个敌我横向的排版还能放得下
另外采用缩放的话整个可显示区域也缩放，显示的内容没变多
![45383](https://user-images.githubusercontent.com/21211204/36936621-bbaf5b52-1f42-11e8-900e-0c238362672b.png)

**Comment by yukixz** [comment]
@deepsea666 本体问题请去 poooi/poi 提……

**Comment by KochiyaOcean** [comment]
之前也说过了，没法针对每个用户的布局一个个做适配，只能做最通用的配置

**Comment by deepsea666** [comment]
@yukixz 
我是想问问这个插件能不能做一个敌我左右而不是上下分的模式，这个应该不是本体的问题

**Comment by KochiyaOcean** [comment]
就算你说的是插件问题你也发错插件了

**Comment by deepsea666** [comment]
这里不是未卜先知的插件？

**Comment by yukixz** [comment]
@deepsea666 未卜先知在poi纵版的时候是左右切分的

**Comment by deepsea666** [comment]
不好意思，我看到battle就直接任务这里是战斗剧透的地方了

**Comment by deepsea666** [comment]
不好意思，看到battle就直接以为这里是战斗剧透的插件了，我去未卜先知那边发问问吧
