### ISSUE TITLE
能否在「浏览」界面增加一个「是否包含活动地图」的单选框

### ISSUE THREAD

**Issue by Sunev** [poooi/plugin-battle-detail#61]
![image](https://user-images.githubusercontent.com/12387091/50736977-09303e00-11ff-11e9-9ac9-6105e8da875c.png)
如图，例如我想查一下之前打3-3用的什么配置，但是因为捞船打了巨多的43-3，我就得一直翻到13页才能找到，相当的麻烦，用正则来查也并不方便。。。

**Comment by Javran** [comment]
出擊視圖恢復之後多少算是解決這問題了,可以直接選擇特定出擊海域的記錄.
