### ISSUE TITLE
23春活以前的战斗记录敌方装备全都出现了显示错误

### ISSUE THREAD

**Issue by Billons007** [poooi/plugin-battle-detail#81]
<img width="1137" alt="Snipaste_2023-06-22_13-57-00" src="https://github.com/poooi/plugin-battle-detail/assets/67461674/c0d873c1-d312-4c37-848e-1203a2d6d908">
大部分都变成了烟雾和356改三

**Comment by Billons007** [comment]
是不是什么地方溢出了？

**Comment by Javran** [comment]
可能是Nov 9, 2022的更新, 深海的id編號從501挪到了1501, 而舊的記錄依舊使用的是之前的編號.

![2023-06-22_18-11](https://github.com/poooi/plugin-battle-detail/assets/1096354/12f24dad-7ba4-4523-9080-5f9142edfe8c)
![2023-06-22_18-12_1](https://github.com/poooi/plugin-battle-detail/assets/1096354/eae5d092-e805-4f27-8696-b5a9c1ef80f5)
